import DemoImage1 from "public/img/demo-image-1.jpg";
import type { EventItemType } from "~/components/Event/EventItem";

export const demoStatusData: EventItemType[] = [
  {
    id: 1,
    name: "This is an Event Name",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
    startDateTime: new Date("2024-03-14T23:00"),
    endDateTime: new Date("2024-03-14T23:00"),
    image: DemoImage1,
    price: 0,
    maxParticipants: undefined,
    inviteLink: undefined,
    address: "this is an address",
    lat: undefined,
    lng: undefined,
    status: "UPCOMING",
    isPrivate: false,
    isFree: true,
    createdAt: new Date("2024/03/13"),
    updatedAt: new Date("2024/03/13"),
    createdBy: {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    eventParticipants: [
      {
        id: "1",
        name: null,
        username: "Brian Tam",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "2",
        name: null,
        username: "Ivan A",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "3",
        name: null,
        username: "Michael P",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
    ],
  },
  {
    id: 2,
    name: "This is an Event Name",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
    startDateTime: new Date("2024-03-14T23:00"),
    endDateTime: new Date("2024-03-14T23:00"),
    image: DemoImage1,
    price: 0,
    maxParticipants: undefined,
    inviteLink: undefined,
    address: "this is an address",
    lat: undefined,
    lng: undefined,
    status: "IN_PROGRESS",
    isPrivate: false,
    isFree: true,
    createdAt: new Date("2024-03-10T23:00"),
    updatedAt: new Date("2024-03-10T23:00"),
    createdBy: {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    eventParticipants: [
      {
        id: "1",
        name: null,
        username: "Brian Tam",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "2",
        name: null,
        username: "Ivan A",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "3",
        name: null,
        username: "Michael P",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
    ],
  },
  {
    id: 3,
    name: "This is an Event Name",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
    startDateTime: new Date("2024-03-14T23:00"),
    endDateTime: new Date("2024-03-14T23:00"),
    image: DemoImage1,
    price: 0,
    maxParticipants: undefined,
    inviteLink: undefined,
    address: "this is an address",
    lat: undefined,
    lng: undefined,
    status: "COMPLETED",
    isPrivate: false,
    isFree: true,
    createdAt: new Date("2024-03-10T23:00"),
    updatedAt: new Date("2024-03-10T23:00"),
    createdBy: {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    eventParticipants: [
      {
        id: "1",
        name: null,
        username: "Brian Tam",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "2",
        name: null,
        username: "Ivan A",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "3",
        name: null,
        username: "Michael P",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
    ],
  },
  {
    id: 4,
    name: "This is an Event Name",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
    startDateTime: new Date("2024-03-14T23:00"),
    endDateTime: new Date("2024-03-14T23:00"),
    image: DemoImage1,
    price: 0,
    maxParticipants: undefined,
    inviteLink: undefined,
    address: "this is an address",
    lat: undefined,
    lng: undefined,
    status: "CANCELED",
    isPrivate: false,
    isFree: true,
    createdAt: new Date("2024-03-10T23:00"),
    updatedAt: new Date("2024-03-10T23:00"),
    createdBy: {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    eventParticipants: [
      {
        id: "1",
        name: null,
        username: "Brian Tam",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "2",
        name: null,
        username: "Ivan A",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
      {
        id: "3",
        name: null,
        username: "Michael P",
        password: null,
        firstName: null,
        lastName: null,
        email: null,
        emailVerified: null,
        role: "USER",
        image: null,
      },
    ],
  },
];

