import DemoImage1 from "public/img/demo-image-1.jpg";
import { iEventItem } from "~/components/Event/EventItem";

const demoStatusData: Array<iEventItem> = [
{
  id: 2,
  name: "This is an Event Name",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
  startDateTime: "2024/03/14 11pm",
  endDateTime: "2024/03/20 11pm",
  image: DemoImage1,
  price: 0,
  maxParticipants: undefined,
  inviteLink: undefined,
  address: "this is an address",
  lat: undefined,
  lng: undefined,
  status: "UPCOMING",
  isPrivate: false,
  isFree: true,
  createdAt: "2024/03/13",
  updatedAt: "2024/03/13",
  host: {
    id: "1",
    name: null,
    username: "Brian Tam",
    password: null,
    firstName: null,
    lastName: null,
    email: null,
    emailVerified: null,
    role: "USER",
    image: null,
  },
  eventParticipants: [
    {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "2",
      name: null,
      username: "Ivan A",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "3",
      name: null,
      username: "Michael P",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
  ],
},
{
  id: 3,
  name: "This is an Event Name",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
  startDateTime: "2024/03/14 11pm",
  endDateTime: "2024/03/20 11pm",
  image: DemoImage1,
  price: 0,
  maxParticipants: undefined,
  inviteLink: undefined,
  address: "this is an address",
  lat: undefined,
  lng: undefined,
  status: "IN_PROGRESS",
  isPrivate: false,
  isFree: true,
  createdAt: "2024/03/13",
  updatedAt: "2024/03/13",
  host: {
    id: "1",
    name: null,
    username: "Brian Tam",
    password: null,
    firstName: null,
    lastName: null,
    email: null,
    emailVerified: null,
    role: "USER",
    image: null,
  },
  eventParticipants: [
    {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "2",
      name: null,
      username: "Ivan A",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "3",
      name: null,
      username: "Michael P",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
  ],
},
{
  id: 3,
  name: "This is an Event Name",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
  startDateTime: "2024/03/14 11pm",
  endDateTime: "2024/03/20 11pm",
  image: DemoImage1,
  price: 0,
  maxParticipants: undefined,
  inviteLink: undefined,
  address: "this is an address",
  lat: undefined,
  lng: undefined,
  status: "COMPLETED",
  isPrivate: false,
  isFree: true,
  createdAt: "2024/03/13",
  updatedAt: "2024/03/13",
  host: {
    id: "1",
    name: null,
    username: "Brian Tam",
    password: null,
    firstName: null,
    lastName: null,
    email: null,
    emailVerified: null,
    role: "USER",
    image: null,
  },
  eventParticipants: [
    {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "2",
      name: null,
      username: "Ivan A",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "3",
      name: null,
      username: "Michael P",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
  ],
},
{
  id: 3,
  name: "This is an Event Name",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod.",
  startDateTime: "2024/03/14 11pm",
  endDateTime: "2024/03/20 11pm",
  image: DemoImage1,
  price: 0,
  maxParticipants: undefined,
  inviteLink: undefined,
  address: "this is an address",
  lat: undefined,
  lng: undefined,
  status: "CANCELED",
  isPrivate: false,
  isFree: true,
  createdAt: "2024/03/13",
  updatedAt: "2024/03/13",
  host: {
    id: "1",
    name: null,
    username: "Brian Tam",
    password: null,
    firstName: null,
    lastName: null,
    email: null,
    emailVerified: null,
    role: "USER",
    image: null,
  },
  eventParticipants: [
    {
      id: "1",
      name: null,
      username: "Brian Tam",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "2",
      name: null,
      username: "Ivan A",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
    {
      id: "3",
      name: null,
      username: "Michael P",
      password: null,
      firstName: null,
      lastName: null,
      email: null,
      emailVerified: null,
      role: "USER",
      image: null,
    },
  ],
}
]

export default demoStatusData